apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bank-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bank-deploy
  minReplicas: 3
  maxReplicas: 10
  metrices:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: utilization
          averageUtilization: 60
